name: Update Space Shooter Game

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:      # Allows you to trigger it manually from the Actions tab

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Required for the amend feature to not clutter history

      - name: Generate Space Shooter Game
        uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'space-shooter.gif'
          strategy: 'random' # The attack pattern of enemies. Can be 'column', 'row', or 'random'
          fps: 40
